### ISSUE TITLE
Asteroids spawning once with StarSystems 

### ISSUE THREAD

**Issue by 00Augustus00** [Starstrider42/Custom-Asteroids#17]
Basically one asteroid will spawn in an entire save, and it's type, orbit, and designation is always the same. I'm using x64, by the way.

**Comment by Starstrider42** [comment]
Closing, as StarSystems has not been maintained since KSP 0.90, and most users have migrated to KerbalGalaxy. If the bug reappears with KerbalGalaxy and/or Kopernicus, please open a new issue.
