### ISSUE TITLE
Asteroids Don't Receive Custom Names Without Custom Spawner

### ISSUE THREAD

**Issue by wtchappell** [Starstrider42/Custom-Asteroids#19]
In an effort to avoid a bug where asteroids spawn until the game chokes, I've disabled the CustomAsteroids spawner in favor of the stock one.

While this did fix the number of asteroids I have, all new asteroids are just named 'Ast. FOO' instead of the titles listed in the config files.

**Comment by Starstrider42** [comment]
@wtchappell, can you tell me what KSP you're using (OS, 32- or 64-bit)? I just installed Custom Asteroids 1.1.0 on a clean Windows KSP 32-bit, and I don't get this problem:

![screenshot0](https://cloud.githubusercontent.com/assets/6760782/11621165/a5f2426a-9cb9-11e5-8486-b6abb6bcb42c.png)

**Comment by Starstrider42** [comment]
Never mind, I saw it in your other post: Linux x64.

**Comment by Starstrider42** [comment]
Since the relevant code has been completely rewritten, this issue does not apply to Custom Asteroids 1.2. Please open a new issue if a similar problem appears again.
