### ISSUE TITLE
Bad forum link in Ckan

### ISSUE THREAD

**Issue by miki-g** [Starstrider42/Custom-Asteroids#37]
now:
https://forum.kerbalspaceprogram.com/index.php?/topic/72785-/
bad

correct:
[https://forum.kerbalspaceprogram.com/index.php?/topic/72785-*](https://forum.kerbalspaceprogram.com/index.php?/topic/72785-*)

**Comment by Starstrider42** [comment]
Ugh, yes, the forum's rules for what's a minimum valid link changed.

Thanks for reporting this, I should have an opportunity to fix it soon.

**Comment by Starstrider42** [comment]
The link works now.
