### ISSUE TITLE
every asteroid is having a stroke

### ISSUE THREAD

**Issue by gnomed-by-steve** [Starstrider42/Custom-Asteroids#40]
### Background Info ###
* Operating System: weenoez 1O
* KSP Version: 1.5.1
* 32-bit/64-bit KSP: 64-bit
* Custom Asteroids Version: 1.5.0

### Issue Description ###
Please describe the problem, including detailed steps to reproduce it.

Every asteroid (and some moons) are having a serious stroke, even on the map screen, the 'roids don't move, but are rotating at break-neck speeds including my kerbal in EVA. I've tried timewarp, but it didn't work. I've heard that this is a vanilla bug, but I haven't been able to reproduce it at all, so I don't know whats wrong here. Side-note: small moons (including dres) are out of orbit, wtf? (maybe i should clarify its out of the set orbit path, like this: / )
                                                  /
                                            O   \
                                                    \

**Comment by Starstrider42** [comment]
Sorry, but I can't seem to reproduce this bug. I've loaded the versions you've listed, but I don't see any unusual behavior in the tracking station, in flight mode, or in map view from flight mode.

Given that Custom Asteroids should not have any effect on moons or EVA kerbals, I suspect this is a bug with another mod. Do you see the same problem with *just* Custom Asteroids and ModuleManager installed?
