### ISSUE TITLE
Specify comet orbit type when using PotatoComet instead of CaCometActive?

### ISSUE THREAD

**Issue by WarpPrime** [Starstrider42/Custom-Asteroids#53]
I'm playing a heavily modded RSS game (no RO/RP-1, it kills my CPU), and have CustomAsteroids already running with some enhancements introduced by myself (Oort cloud objects, vulcanoids, interstellar comets, etc.). I've replaced almost all the instances of `CaCometActive` with `PotatoComet` to merge with the stock comet system so I can collect actual comet samples for science. However, all the comet objects spawned are labeled "Intermediate period," regardless of what orbit it is in.

I'd like for a parameter when using `PotatoComet` called something with the syntax of 
```
ASTEROIDGROUP
{
    // stuff...
    asteroidTypes // copied from the oort asteroid group except CaCometActive is now PotatoComet, integrating into the stock comet system
    {
	key = 1.0 PotatoComet
    }
    CaCometOrbit // only used if PotatoComet is mentioned in the asteroidTypes keys.
    {
        type = short // intermediate, long, interstellar
    }
    // more stuff...
}
```

I would really appreciate it if you could integrate this into the next CustomAsteroids update. Thanks!

**Comment by WarpPrime** [comment]
I found on the API syntax that there was an `orbitType` class that I could use, but it seems not to be working in my RSS save.

**Comment by Starstrider42** [comment]
Sorry, can you give more detail? The [default config for RSS](https://github.com/KSP-RO/RealSolarSystem/blob/master/GameData/RealSolarSystem/Compatibility/CustomAsteroids.cfg) also uses `orbitType`, and it was tested to work there. What versions of KSP, Custom Asteroids, and RSS are you using?
